name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or 'main' if your default branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install --save gh-pages

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx gh-pages -d dist
